### ISSUE TITLE
bad signature twrp-3.7.0_9-0-fajita.img

### ISSUE THREAD

**Issue by mkgvt** [TeamWin/twrpme#145]
#### WHAT STEPS WILL REPRODUCE THE PROBLEM?

```
$ curl -LO https://dl.twrp.me/public.asc
$ gpg --import public.asc
$ gpg -k TeamWin
pub   rsa4096 2016-11-27 [SC]
      95707D42307C9D41D09BF7091D8597D7891A43DF
uid           [ unknown] TeamWin <admin@teamw.in>
sub   rsa4096 2016-11-27 [E]
$ curl -LO https://dl.twrp.me/fajita/twrp-3.7.0_9-0-fajita.img
$ curl -LO https://dl.twrp.me/fajita/twrp-3.7.0_9-0-fajita.img.asc
$ gpg --verify twrp-3.7.0_9-0-fajita.img.asc twrp-3.7.0_9-0-fajita.img
gpg: Signature made Mon 10 Oct 2022 08:52:13 PM EDT
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]
```

#### WHAT IS THE EXPECTED RESULT?

The signature should be good (like it was for a previous version):
```
gpg: Good signature from "TeamWin <admin@teamw.in>" [unknown]
```

#### WHAT HAPPENS INSTEAD?

```
gpg: BAD signature from "TeamWin <admin@teamw.in>" [unknown]
```

**Comment by bigbiff** [comment]
This has been fixed. Thanks for the report.

**Comment by mkgvt** [comment]
I went to the [download page](https://dl.twrp.me/fajita/twrp-3.7.0_9-0-fajita.img.html) and re-downloaded both the image and the signature. I'm still getting the same "BAD signature" error. How do I get access to the fix?

**Comment by bigbiff** [comment]
jenkins@ns103310:/www/dl.twrp.me/fajita$ gpg --verify twrp-3.7.0_9-0-fajita.img.asc
gpg: assuming signed data in 'twrp-3.7.0_9-0-fajita.img'
gpg: Signature made Sat 05 Nov 2022 10:13:05 PM UTC
gpg:                using RSA key 95707D42307C9D41D09BF7091D8597D7891A43DF
gpg: Good signature from "TeamWin <admin@teamw.in>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 9570 7D42 307C 9D41 D09B  F709 1D85 97D7 891A 43DF

Can you check the sha256 matches what you downloaded?

**Comment by mkgvt** [comment]
Doh! User error. I right clicked to copy the image link then used curl to download. That downloads a web page not the image. Downloading directly within the browser works. The SHA256 verifies and the signature is good. Thanks.
