### ISSUE TITLE
Can't message to team

### ISSUE THREAD

**Issue by AlexM0rtis** [TeamWin/twrpme#33]
When i'm trying send a message in your site, i'm getting error
```
502 Bad Gateway

nginx/1.10.0 (Ubuntu)
```
So can you fix that bug, or give me your mail.
P.S. I wanna become a maintainer.

**Comment by bigbiff** [comment]
Thanks for the report. We moved to a new host and I needed some stuff to setup. It is now fixed.

**Comment by Rortiz2005** [comment]
It still does not work, when I try to contact with us it gives me the error:
502 Bad Gateway
nginx / 1.10.3 (Ubuntu)

**Comment by bigbiff** [comment]
What URL?
